name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  batch: false
  branches:
    include:
    - main

pr:
  autoCancel: true
  branches:
    include:
    - main
  drafts: true

schedules:
- cron: "0 0 * * 1"
  displayName: Weekly build Monday Midnight
  branches:
    include:
    - main
  always: true

resources:
- repo: self

pool:
  vmImage: 'windows-latest'

variables:
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

stages:
- stage: 'CI'
  displayName: 'Continous Integration'
  jobs:
  - job: 'Init'
    displayName: 'Initialization'
    continueOnError: false
    pool:
      vmImage: 'windows-latest'
    workspace:
      clean: all
    steps:
    - checkout: none

    - task: PowerShell@1
      displayName: 'Set Build Version'
      condition: and(succeeded(), ne(variables.isMain, true))
      inputs:
        scriptType: inlineScript
        inlineScript: |
          Write-Output $env:BUILD_SOURCEBRANCHNAME

          If ($env:BUILD_SOURCEBRANCHNAME -ne "master"){
            Write-Output ("##vso[build.updatebuildnumber]" + $env:BUILD_BUILDNUMBER+"-alpha")
            Write-Output "setting version as -alpha"
          }

  - job: 'Validation'
    displayName: 'Validate & Package Templates'
    continueOnError: false
    dependsOn: 'Init'
    pool:
      vmImage: 'windows-latest'
    workspace:
      clean: all
    steps:
    - checkout: self

    - task: PowerShell@2
      displayName: 'Perform ARM TTK Test Run'
      inputs:
        filePath: '$(Build.SourcesDirectory)\Utilities\Run-ARMTTK.ps1'
        arguments: '-outputPath $(Common.TestResultsDirectory)'
        failOnStderr: true
        showWarnings: true
        pwsh: true
        workingDirectory: $(Build.SourcesDirectory)

    - task: PublishTestResults@2
      displayName: 'Publish ARM TTK Test Run Results'
      inputs:
        testResultsFormat: 'NUnit'
        testResultsFiles: '*.nunit'
        searchFolder: '$(Common.TestResultsDirectory)'
        mergeTestResults: true
        failTaskOnFailedTests: true
        testRunTitle: 'ARM TTK'
