name: learn-github-actions
on: [push]
jobs:
  Validate-ARM:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: |
          Write-host $PSVersionTable.PSVersion.Major $PSVersionTable.PSRemotingProtocolVersion.Minor
          Set-PSRepository PSGallery -InstallationPolicy trusted
          Install-Module -Name Pester -RequiredVersion 4.10.1 -confirm:$false -Force
          ./Utilities/Invoke-ARMTTK.ps1
        shell: pwsh