name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: |
          ./Utilities/Invoke-ARMTTK.ps1
        shell: pwsh