name: TemplateValidation
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron: '30 0 * * 1'
      branches:
        - main
  workflow_dispatch:
jobs:
  Validate-ARM:
    name: Validate ARM
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Invoke ARM TTK
        run: |
          ./Utilities/Invoke-ARMTTK.ps1
        shell: pwsh

  Validate-Bicep:
    name: Validate BICEP
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Invoke BICEP Build
        run: |
          ./Utilities/Invoke-BicepBuild.ps1
        shell: pwsh
